CREATE SCHEMA IF NOT EXISTS scheduling;

CREATE TABLE IF NOT EXISTS scheduling.appointments -- naming is hard, just didn't want schema and table the same
(
    id          serial PRIMARY KEY, -- autogenerated id
    trainer_id  text not null,               -- likely a foreign key, but not part of prompt
    user_id     text not null,               -- likely a foreign key, but not part of prompt
    starts_at   timestamptz not null,
    ends_at     timestamptz not null,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    canceled_at timestamptz         -- not part of prompt, but i tend to have an "archive" timestamp if record not moved to archive table
);

CREATE UNIQUE INDEX if not exists trainer_scheduled on scheduling.appointments (trainer_id, starts_at, ends_at) where canceled_at is null;
